version: 2

# List of jobs
jobs:

    # Install python dependencies using virtual env
    install-zip-lambda:
        working_directory: ~/builder
        docker:
            - image: amazonlinux:2
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout

            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}

            - run:
                name: Yum Update
                command: yum -y update

            - run:
                name: Install python
                command: yum install -y python2-pip

            - run:
                name: Install Virtualenv
                command: pip install --no-input virtualenv

            # Download and cache dependencies
            # - restore_cache:
            #     keys:
            #     - v1-dependencies-{{ checksum "requirements.txt" }}
            #     # fallback to using the latest cache if no exact match is found
            #     - v1-dependencies-

            # - run:
            #     name: install dependencies
            #     command: |
            #     python3 -m venv venv
            #     . venv/bin/activate
            #     pip install -r requirements.txt

            # - save_cache:
            #     paths:
            #     - ./venv
            #     key: v1-dependencies-{{ checksum "requirements.txt" }}

            # run tests!
            # this example uses Django's built-in test-runner
            # other common Python testing frameworks include pytest and nose
            # https://pytest.org
            # https://nose.readthedocs.io
            # - run:
            #     name: run tests
            #     command: |
            #       . venv/bin/activate
            #       python manage.py test

            # - store_artifacts:
            #     path: test-reports
            #     destination: test-reports
