AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Circle-ci-test-python

Resources:

  Transunion:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      CodeUri: .
      Runtime: python2.7
      Timeout: 60000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: post
